update definition of sb based on reviewer comments
nmfs-fish-tools/fishdictionary pull request #50
Opened 2024-07-10 14:25 UTC by chantelwetzel-noaa

Revised the definition of SB based on reviewer comments.

2024-07-10 14:50 UTC, kellijohnson-NOAA requested changes
There are a few typos but the biggest thing that I found was the use of "stock" where we want to use population.

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' defined as the product of weight-at-age and the proportion
weight-at-age should be "weight at age"

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' mature-at-age. Alternatively, it can be defined as the biomass of
mature-at-age should be mature at age

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' at 50 percent maturity.” or the total biomass of fish of reproductive
remove the full stop after maturity

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' age during the breeding season of a stock. Most often used as a proxy
Remove "of a stock"

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' abundance of the various age classes composing the stock and their
change stock to population

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on R/SpawningBiomass.R
> +#' for measuring egg production, the spawning biomass depends on the
"Most often used as a proxy for measuring egg production" does not seem to be tied to the rest of the sentence 🤷 . With the comma after the clause it appears to be a qualifying statement but I am not seeing the connection. Perhaps make it its own sentence and put it at the end of the paragraph.

2024-07-10 14:50 UTC, kellijohnson-NOAA commented on man/Catch.Rd
I am guessing that this change in Catch.Rd is a byproduct of some other commit without the documentation being rendered? Perhaps we should move it into its own commit?

2024-07-10 14:54 UTC, chantelwetzel-noaa commented on R/SpawningBiomass.R
> +#' age during the breeding season of a stock. Most often used as a proxy
That is our bad, since it was in the original text too.  I agree that this should be revised.

2024-07-10 15:04 UTC, chantelwetzel-noaa commented
@kellijohnson-NOAA I have separated out the catch edits to its own commit and have made the suggested edits for spawning biomass.

2024-07-10 15:05 UTC, kellijohnson-NOAA approved these changes

2024-07-10 17:52 UTC, chantelwetzel-noaa commented
@Bai-Li-NOAA I think me question to you in this review is about the Shiny page.  Should the process to be to publish the revised webpage post-merging in the pull request or does that happen automatically with the github actions?  Thank you

2024-07-10 17:58 UTC, Bai-Li-NOAA commented
@chantelwetzel-noaa, this is embarrassing, I don't remember how it works. @ChristineStawitz-NOAA might be able to provide a better answer to this question.

2024-07-10 18:21 UTC, k-doering-NOAA commented
@chantelwetzel-noaa and @Bai-Li-NOAA , sorry for lurking, but I think I can help a bit with this one!

I just gave both of you edit permissions on the Shiny app on Posit connect. 

It looks like it was published to deploy from a branch called shiny_app and to check automatically for updates on the branch. However, I think the branch no longer exists, so it can't pull in updates. 
![image](https://github.com/nmfs-fish-tools/fishdictionary/assets/48930335/f81a5f4e-0c04-4ae4-a87c-f5da237280b6)


Therefore, it may need to be re-deployed from an existing branch of your choosing, if you would like it to stay automatically up to date. One note is that the manifest file may need to be updated periodically (either manually and pushed to the branch, or through a github action). I didn't look at the ghas in this repo, so apologize if this is already being dealt with!

2024-07-11 14:01 UTC, chantelwetzel-noaa commented
@k-doering-NOAA You are the kind of lurker that everyone loves.  Thank you for taking the time to look at this.  I'll see If I can get the set back up based on your suggestions.

2024-07-11 14:02 UTC, merged